### ISSUE TITLE
Problemas con parametro fields en comando clients

### ISSUE THREAD

**Issue by chumager** [gmontero/API-Bsale#1]
Hola qué tal?

cuando hago esta consulta:` https://api.bsale.cl/v1/clients.json?fields=[firstname,lastname]
`
me genera el siguiente error:

{
  "error": "Sorry there was a nasty error - missing attribute: id_lista_precio"
}

por si acaso no tengo problemas con consultas sin el parámetro fields, no es error de consulta.

en el modelo de datos de clientes no aparece que tenga phone o email, pero en el post si aparece, y consultando todos los registros encuentro que hay algunos clientes con phone y correo, pero no aparece en la documentación.

me podrías clarificar si el modelo tiene en el cliente dichos campos o en el contacto...

Saludos

**Comment by crojas** [comment]
Hola!

Puede deberse a una mala configuracion de la instancia en que estas haciendo pruebas, contacta a nuestro equipo de soporte (support@imaginex.cl) para ver este tema.

Saludos
