### ISSUE TITLE
Obtención de datos por omisión...

### ISSUE THREAD

**Issue by chumager** [gmontero/API-Bsale#2]
Hola qué tal?

No veo ni un comando en la API que permita tener información de la configuración del usuario, como por ejemplo la lista de precios por omisión que se usa en la plataforma, ya que los clientes que no se les asigna lista de precios usan la por omisión en la plataforma, cómo puedo saber cuál es?

**Comment by crojas** [comment]
Hola!

Lamentablemente esa configuracion aún no esta disponible por API

Saludos
